import { AuditLog } from '../types';

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    actorId: 'user-admin-1',
    actorName: 'Victoria Sterling',
    actorRole: 'admin',
    actorEmail: 'admin@shopsphere.com',
    action: 'PRODUCT_APPROVED',
    resourceType: 'product',
    resourceId: 'prod-iphone-15-pro',
    details: 'Approved product listing "Apple iPhone 15 Pro Max - Titanium" submitted by seller TechVault Official.',
    ipAddress: '192.0.2.14',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/121.0.0.0',
    timestamp: '2024-02-14T10:15:00Z',
  },
  {
    id: 'audit-2',
    actorId: 'user-admin-1',
    actorName: 'Victoria Sterling',
    actorRole: 'admin',
    actorEmail: 'admin@shopsphere.com',
    action: 'SELLER_VERIFIED',
    resourceType: 'seller',
    resourceId: 'seller-tech-vault',
    details: 'Verified business registration documents and approved tier upgrade to Platinum.',
    ipAddress: '192.0.2.14',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/121.0.0.0',
    timestamp: '2024-02-10T14:30:00Z',
  },
  {
    id: 'audit-3',
    actorId: 'user-admin-1',
    actorName: 'Victoria Sterling',
    actorRole: 'admin',
    actorEmail: 'admin@shopsphere.com',
    action: 'GLOBAL_COUPON_CREATED',
    resourceType: 'coupon',
    resourceId: 'coup-tech50',
    details: 'Published platform voucher TECH50 ($50 off electronics category).',
    ipAddress: '192.0.2.14',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/121.0.0.0',
    timestamp: '2024-02-01T08:00:00Z',
  },
];
