import { Brand } from '../types';

export const MOCK_BRANDS: Brand[] = [
  {
    id: 'brand-apple',
    name: 'Apple',
    slug: 'apple',
    logoUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=120&auto=format&fit=crop&q=80',
    description: 'Pioneering premium consumer electronics, laptops, and smart wearables.',
    website: 'https://apple.com',
    featured: true,
  },
  {
    id: 'brand-sony',
    name: 'Sony',
    slug: 'sony',
    logoUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=120&auto=format&fit=crop&q=80',
    description: 'World leader in audiovisual technology, gaming, and professional cameras.',
    website: 'https://sony.com',
    featured: true,
  },
  {
    id: 'brand-samsung',
    name: 'Samsung',
    slug: 'samsung',
    logoUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=120&auto=format&fit=crop&q=80',
    description: 'Innovative displays, smartphones, home appliances, and memory storage.',
    website: 'https://samsung.com',
    featured: true,
  },
  {
    id: 'brand-nike',
    name: 'Nike',
    slug: 'nike',
    logoUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&auto=format&fit=crop&q=80',
    description: 'Iconic athletic footwear, sports apparel, and high-performance equipment.',
    website: 'https://nike.com',
    featured: true,
  },
  {
    id: 'brand-bose',
    name: 'Bose',
    slug: 'bose',
    logoUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=120&auto=format&fit=crop&q=80',
    description: 'Legendary noise-cancelling headphones and premium home audio systems.',
    website: 'https://bose.com',
    featured: true,
  },
  {
    id: 'brand-dyson',
    name: 'Dyson',
    slug: 'dyson',
    logoUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=120&auto=format&fit=crop&q=80',
    description: 'Groundbreaking airflow engineering for haircare, air purification, and vacuums.',
    website: 'https://dyson.com',
    featured: true,
  },
  {
    id: 'brand-logitech',
    name: 'Logitech G',
    slug: 'logitech',
    logoUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=120&auto=format&fit=crop&q=80',
    description: 'High performance gaming peripherals, mechanical keyboards, and precision mice.',
    website: 'https://logitechg.com',
    featured: false,
  },
  {
    id: 'brand-rolex',
    name: 'Rolex',
    slug: 'rolex',
    logoUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=120&auto=format&fit=crop&q=80',
    description: 'Swiss luxury watchmaking craftsmanship and timeless horological elegance.',
    website: 'https://rolex.com',
    featured: true,
  },
];
