import { Category } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-electronics',
    name: 'Electronics & Gadgets',
    slug: 'electronics',
    description: 'Next-gen smartphones, laptops, smart home devices, and audiovisual gear.',
    icon: 'Laptop',
    imageUrl: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&auto=format&fit=crop&q=80',
    itemCount: 1420,
    featured: true,
    subcategories: [
      { id: 'sub-smartphones', name: 'Smartphones & Tablets', slug: 'smartphones-tablets', parentId: 'cat-electronics', itemCount: 420 },
      { id: 'sub-laptops', name: 'Laptops & Desktops', slug: 'laptops-desktops', parentId: 'cat-electronics', itemCount: 310 },
      { id: 'sub-audio', name: 'Headphones & Audio', slug: 'headphones-audio', parentId: 'cat-electronics', itemCount: 280 },
      { id: 'sub-wearables', name: 'Smartwatches & Wearables', slug: 'smartwatches-wearables', parentId: 'cat-electronics', itemCount: 190 },
      { id: 'sub-cameras', name: 'Cameras & Photography', slug: 'cameras-photography', parentId: 'cat-electronics', itemCount: 220 },
    ],
  },
  {
    id: 'cat-fashion',
    name: 'Fashion & Apparel',
    slug: 'fashion',
    description: 'Designer clothing, footwear, luxury accessories, and everyday essentials.',
    icon: 'Shirt',
    imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&auto=format&fit=crop&q=80',
    itemCount: 2350,
    featured: true,
    subcategories: [
      { id: 'sub-mens-clothing', name: "Men's Fashion", slug: 'mens-fashion', parentId: 'cat-fashion', itemCount: 780 },
      { id: 'sub-womens-clothing', name: "Women's Fashion", slug: 'womens-fashion', parentId: 'cat-fashion', itemCount: 950 },
      { id: 'sub-footwear', name: 'Footwear & Sneakers', slug: 'footwear-sneakers', parentId: 'cat-fashion', itemCount: 340 },
      { id: 'sub-watches-jewelry', name: 'Watches & Jewelry', slug: 'watches-jewelry', parentId: 'cat-fashion', itemCount: 280 },
    ],
  },
  {
    id: 'cat-home-living',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Modern furniture, home decor, cookware, and smart kitchen appliances.',
    icon: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    itemCount: 1890,
    featured: true,
    subcategories: [
      { id: 'sub-furniture', name: 'Living Room Furniture', slug: 'living-furniture', parentId: 'cat-home-living', itemCount: 510 },
      { id: 'sub-kitchen', name: 'Kitchen & Dining', slug: 'kitchen-dining', parentId: 'cat-home-living', itemCount: 620 },
      { id: 'sub-bedding', name: 'Bedding & Bath', slug: 'bedding-bath', parentId: 'cat-home-living', itemCount: 380 },
      { id: 'sub-decor', name: 'Lighting & Decor', slug: 'lighting-decor', parentId: 'cat-home-living', itemCount: 380 },
    ],
  },
  {
    id: 'cat-beauty',
    name: 'Beauty & Wellness',
    slug: 'beauty-wellness',
    description: 'Skincare, premium fragrances, cosmetics, and organic wellness essentials.',
    icon: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80',
    itemCount: 940,
    featured: true,
    subcategories: [
      { id: 'sub-skincare', name: 'Luxury Skincare', slug: 'luxury-skincare', parentId: 'cat-beauty', itemCount: 410 },
      { id: 'sub-fragrances', name: 'Perfumes & Fragrances', slug: 'fragrances', parentId: 'cat-beauty', itemCount: 230 },
      { id: 'sub-haircare', name: 'Hair Care & Styling', slug: 'hair-care', parentId: 'cat-beauty', itemCount: 180 },
      { id: 'sub-wellness', name: 'Supplements & Wellness', slug: 'wellness', parentId: 'cat-beauty', itemCount: 120 },
    ],
  },
  {
    id: 'cat-sports',
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    description: 'Cardio equipment, gym apparel, outdoor hiking gear, and sports accessories.',
    icon: 'Dumbbell',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    itemCount: 760,
    featured: false,
    subcategories: [
      { id: 'sub-gym', name: 'Gym & Fitness Equipment', slug: 'gym-equipment', parentId: 'cat-sports', itemCount: 310 },
      { id: 'sub-activewear', name: 'Activewear', slug: 'activewear', parentId: 'cat-sports', itemCount: 290 },
      { id: 'sub-outdoor', name: 'Outdoor & Camping', slug: 'outdoor-camping', parentId: 'cat-sports', itemCount: 160 },
    ],
  },
  {
    id: 'cat-gaming',
    name: 'Gaming & Entertainment',
    slug: 'gaming',
    description: 'Consoles, high-refresh gaming monitors, mechanical keyboards, and VR headsets.',
    icon: 'Gamepad2',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    itemCount: 680,
    featured: true,
    subcategories: [
      { id: 'sub-consoles', name: 'Gaming Consoles', slug: 'gaming-consoles', parentId: 'cat-gaming', itemCount: 140 },
      { id: 'sub-peripherals', name: 'Keyboards, Mice & Headsets', slug: 'gaming-peripherals', parentId: 'cat-gaming', itemCount: 320 },
      { id: 'sub-pc-parts', name: 'Graphics Cards & PC Hardware', slug: 'pc-hardware', parentId: 'cat-gaming', itemCount: 220 },
    ],
  },
];
