import { Order } from '../types';
import { MOCK_PRODUCTS } from './products';

const iphone = MOCK_PRODUCTS[0];
const sonyHeadphones = MOCK_PRODUCTS[1];
const nikeJordan = MOCK_PRODUCTS[3];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-98214',
    orderNumber: 'ORD-2024-98214',
    userId: 'user-customer-1',
    customerName: 'Alex Morgan',
    customerEmail: 'customer@shopsphere.com',
    customerPhone: '+1 (555) 381-9920',
    items: [
      {
        id: 'item-1',
        orderId: 'ord-98214',
        productId: iphone.id,
        variantId: iphone.variants[0].id,
        sellerId: iphone.sellerId,
        sellerName: iphone.sellerName,
        productTitle: iphone.title,
        productImage: iphone.images[0].url,
        sku: iphone.variants[0].sku,
        attributes: iphone.variants[0].attributes,
        quantity: 1,
        unitPrice: 1199.00,
        totalPrice: 1199.00,
        product: iphone,
        variant: iphone.variants[0],
      },
      {
        id: 'item-2',
        orderId: 'ord-98214',
        productId: sonyHeadphones.id,
        variantId: sonyHeadphones.variants[0].id,
        sellerId: sonyHeadphones.sellerId,
        sellerName: sonyHeadphones.sellerName,
        productTitle: sonyHeadphones.title,
        productImage: sonyHeadphones.images[0].url,
        sku: sonyHeadphones.variants[0].sku,
        attributes: sonyHeadphones.variants[0].attributes,
        quantity: 1,
        unitPrice: 348.00,
        totalPrice: 348.00,
        product: sonyHeadphones,
        variant: sonyHeadphones.variants[0],
      },
    ],
    shippingAddress: {
      id: 'addr-cust-1',
      fullName: 'Alex Morgan',
      phone: '+1 (555) 381-9920',
      street: '452 Pine Hill Road',
      apartment: 'Suite 4B',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
      country: 'United States',
      type: 'home',
    },
    billingAddress: {
      id: 'addr-cust-1',
      fullName: 'Alex Morgan',
      phone: '+1 (555) 381-9920',
      street: '452 Pine Hill Road',
      apartment: 'Suite 4B',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
      country: 'United States',
      type: 'home',
    },
    shippingCarrier: 'FedEx Priority Overnight',
    shippingTrackingNumber: 'FDX-8829-1940-WA',
    estimatedDeliveryDate: '2024-02-18T17:00:00Z',
    deliveredAt: '2024-02-18T14:22:00Z',
    status: 'delivered',
    subtotal: 1547.00,
    discountAmount: 50.00,
    couponCode: 'WELCOME20',
    taxAmount: 119.76,
    shippingCost: 0.00,
    grandTotal: 1616.76,
    payment: {
      method: 'credit_card',
      transactionId: 'TXN-998231-STRIPE',
      status: 'completed',
      paidAt: '2024-02-16T10:14:00Z',
      cardLastFour: '4242',
      cardBrand: 'Visa',
      amount: 1616.76,
    },
    trackingEvents: [
      {
        id: 'trk-1',
        timestamp: '2024-02-16T10:14:00Z',
        status: 'payment_confirmed',
        title: 'Payment Confirmed & Order Placed',
        description: 'Payment authorized via Visa ending in 4242. Order verified by fraud protection.',
        location: 'Seattle, WA',
      },
      {
        id: 'trk-2',
        timestamp: '2024-02-16T15:30:00Z',
        status: 'processing',
        title: 'Packed & Ready for Dispatch',
        description: 'TechVault logistics center has packaged items with serialized anti-tamper seals.',
        location: 'San Jose Logistics Hub, CA',
      },
      {
        id: 'trk-3',
        timestamp: '2024-02-17T08:15:00Z',
        status: 'shipped',
        title: 'In Transit with FedEx',
        description: 'Package scanned at sorting facility and dispatched onto regional flight.',
        location: 'Oakland Air Hub, CA',
        carrierName: 'FedEx Express',
        trackingNumber: 'FDX-8829-1940-WA',
      },
      {
        id: 'trk-4',
        timestamp: '2024-02-18T07:45:00Z',
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Courier is on route to delivery destination. Signature verification enabled.',
        location: 'Seattle Downtown Delivery Hub, WA',
      },
      {
        id: 'trk-5',
        timestamp: '2024-02-18T14:22:00Z',
        status: 'delivered',
        title: 'Delivered to Resident',
        description: 'Package handed directly to Alex Morgan. Proof of delivery signature captured.',
        location: 'Seattle, WA',
      },
    ],
    createdAt: '2024-02-16T10:14:00Z',
    updatedAt: '2024-02-18T14:22:00Z',
  },
  {
    id: 'ord-98255',
    orderNumber: 'ORD-2024-98255',
    userId: 'user-customer-1',
    customerName: 'Alex Morgan',
    customerEmail: 'customer@shopsphere.com',
    customerPhone: '+1 (555) 381-9920',
    items: [
      {
        id: 'item-3',
        orderId: 'ord-98255',
        productId: nikeJordan.id,
        variantId: nikeJordan.variants[0].id,
        sellerId: nikeJordan.sellerId,
        sellerName: nikeJordan.sellerName,
        productTitle: nikeJordan.title,
        productImage: nikeJordan.images[0].url,
        sku: nikeJordan.variants[0].sku,
        attributes: nikeJordan.variants[0].attributes,
        quantity: 1,
        unitPrice: 180.00,
        totalPrice: 180.00,
        product: nikeJordan,
        variant: nikeJordan.variants[0],
      },
    ],
    shippingAddress: {
      id: 'addr-cust-1',
      fullName: 'Alex Morgan',
      phone: '+1 (555) 381-9920',
      street: '452 Pine Hill Road',
      apartment: 'Suite 4B',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
      country: 'United States',
      type: 'home',
    },
    billingAddress: {
      id: 'addr-cust-1',
      fullName: 'Alex Morgan',
      phone: '+1 (555) 381-9920',
      street: '452 Pine Hill Road',
      apartment: 'Suite 4B',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
      country: 'United States',
      type: 'home',
    },
    shippingCarrier: 'UPS Ground Eco',
    shippingTrackingNumber: '1Z-992-A81-9920',
    estimatedDeliveryDate: '2024-02-24T18:00:00Z',
    status: 'shipped',
    subtotal: 180.00,
    discountAmount: 0.00,
    taxAmount: 14.40,
    shippingCost: 8.50,
    grandTotal: 202.90,
    payment: {
      method: 'upi',
      transactionId: 'UPI-REF-99120489',
      status: 'completed',
      paidAt: '2024-02-20T11:00:00Z',
      upiId: 'alex.morgan@okaxis',
      amount: 202.90,
    },
    trackingEvents: [
      {
        id: 'trk-201',
        timestamp: '2024-02-20T11:00:00Z',
        status: 'payment_confirmed',
        title: 'Order Placed & Verified',
        description: 'Payment captured via UPI reference 99120489.',
        location: 'Seattle, WA',
      },
      {
        id: 'trk-202',
        timestamp: '2024-02-21T10:00:00Z',
        status: 'shipped',
        title: 'Package In Transit',
        description: 'Dispatched from Portland Aura fulfillment center.',
        location: 'Portland Sorting Facility, OR',
        carrierName: 'UPS Ground',
        trackingNumber: '1Z-992-A81-9920',
      },
    ],
    createdAt: '2024-02-20T11:00:00Z',
    updatedAt: '2024-02-21T10:00:00Z',
  },
];
