import { Product } from '../types';
import { MOCK_CATEGORIES } from './categories';
import { MOCK_BRANDS } from './brands';

const electronicsCategory = MOCK_CATEGORIES[0];
const fashionCategory = MOCK_CATEGORIES[1];
const homeCategory = MOCK_CATEGORIES[2];
const beautyCategory = MOCK_CATEGORIES[3];
const gamingCategory = MOCK_CATEGORIES[5];

const appleBrand = MOCK_BRANDS[0];
const sonyBrand = MOCK_BRANDS[1];
const nikeBrand = MOCK_BRANDS[3];
const boseBrand = MOCK_BRANDS[4];
const dysonBrand = MOCK_BRANDS[5];
const logitechBrand = MOCK_BRANDS[6];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-iphone-15-pro',
    sellerId: 'seller-tech-vault',
    sellerName: 'TechVault Official',
    title: 'Apple iPhone 15 Pro Max - Titanium',
    slug: 'apple-iphone-15-pro-max-titanium',
    shortDescription: 'Forged in aerospace-grade titanium with the breakthrough A17 Pro chip and customizable Action button.',
    description: `iPhone 15 Pro Max is the first iPhone to feature an aerospace‑grade titanium design, using the same alloy that spacecraft use for missions to Mars. Titanium has one of the best strength‑to‑weight ratios of any metal, making these our lightest Pro models ever.

The A17 Pro chip brings the biggest redesign in the history of Apple GPUs, delivering next-level gaming experiences with hardware-accelerated ray tracing. Capture incredible detail with the 48MP Main camera and 5x optical zoom on the iPhone 15 Pro Max telephoto lens.`,
    brand: appleBrand,
    category: electronicsCategory,
    subCategory: electronicsCategory.subcategories?.[0],
    tags: ['apple', 'iphone', 'flagship', 'titanium', '5g', 'smartphone', 'oled'],
    price: 1199.00,
    originalPrice: 1299.00,
    discountPercentage: 8,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 48,
    sku: 'IPH15PM-MASTER',
    images: [
      { id: 'img-1', url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80', altText: 'iPhone 15 Pro Natural Titanium', isPrimary: true, order: 1 },
      { id: 'img-2', url: 'https://images.unsplash.com/photo-1695048065057-de0281b3bc2e?w=800&auto=format&fit=crop&q=80', altText: 'iPhone 15 Pro Titanium Edge', isPrimary: false, order: 2 },
      { id: 'img-3', url: 'https://images.unsplash.com/photo-1695048132959-1e1b853a4798?w=800&auto=format&fit=crop&q=80', altText: 'iPhone 15 Pro Camera Lens', isPrimary: false, order: 3 },
    ],
    attributes: [
      {
        id: 'attr-color',
        name: 'Color',
        type: 'color',
        options: [
          { id: 'col-nat', name: 'Natural Titanium', value: '#9A958E' },
          { id: 'col-blue', name: 'Blue Titanium', value: '#2C3442' },
          { id: 'col-black', name: 'Black Titanium', value: '#1F2022' },
          { id: 'col-white', name: 'White Titanium', value: '#F3F2EE' },
        ],
      },
      {
        id: 'attr-storage',
        name: 'Storage',
        type: 'select',
        options: [
          { id: 'stor-256', name: '256GB', value: '256gb' },
          { id: 'stor-512', name: '512GB', value: '512gb' },
          { id: 'stor-1tb', name: '1TB', value: '1tb' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-15pm-nat-256',
        productId: 'prod-iphone-15-pro',
        sku: 'IPH15PM-NAT-256',
        title: 'Natural Titanium / 256GB',
        price: 1199.00,
        originalPrice: 1299.00,
        inventoryQuantity: 18,
        stockStatus: 'in_stock',
        attributes: { Color: 'Natural Titanium', Storage: '256GB' },
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      },
      {
        id: 'var-15pm-nat-512',
        productId: 'prod-iphone-15-pro',
        sku: 'IPH15PM-NAT-512',
        title: 'Natural Titanium / 512GB',
        price: 1399.00,
        originalPrice: 1499.00,
        inventoryQuantity: 12,
        stockStatus: 'in_stock',
        attributes: { Color: 'Natural Titanium', Storage: '512GB' },
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      },
      {
        id: 'var-15pm-blue-256',
        productId: 'prod-iphone-15-pro',
        sku: 'IPH15PM-BLU-256',
        title: 'Blue Titanium / 256GB',
        price: 1199.00,
        originalPrice: 1299.00,
        inventoryQuantity: 10,
        stockStatus: 'in_stock',
        attributes: { Color: 'Blue Titanium', Storage: '256GB' },
        imageUrl: 'https://images.unsplash.com/photo-1695048065057-de0281b3bc2e?w=800&auto=format&fit=crop&q=80',
      },
      {
        id: 'var-15pm-black-1tb',
        productId: 'prod-iphone-15-pro',
        sku: 'IPH15PM-BLK-1TB',
        title: 'Black Titanium / 1TB',
        price: 1599.00,
        originalPrice: 1699.00,
        inventoryQuantity: 8,
        stockStatus: 'in_stock',
        attributes: { Color: 'Black Titanium', Storage: '1TB' },
        imageUrl: 'https://images.unsplash.com/photo-1695048132959-1e1b853a4798?w=800&auto=format&fit=crop&q=80',
      },
    ],
    specifications: [
      { group: 'Display', key: 'Screen Size', value: '6.7-inch Super Retina XDR OLED' },
      { group: 'Display', key: 'Refresh Rate', value: '120Hz ProMotion Technology' },
      { group: 'Performance', key: 'Processor', value: 'A17 Pro Chip (3nm) with 6-core GPU' },
      { group: 'Camera', key: 'Main Sensor', value: '48MP Quad-Pixel with Sensor-shift OIS' },
      { group: 'Camera', key: 'Telephoto', value: '12MP 5x Optical Zoom (120mm focal length)' },
      { group: 'Battery', key: 'Video Playback', value: 'Up to 29 hours' },
      { group: 'Build', key: 'Material', value: 'Titanium frame with Ceramic Shield front' },
      { group: 'Connectivity', key: 'Port', value: 'USB-C supporting USB 3 speeds up to 10Gb/s' },
    ],
    rating: 4.9,
    reviewCount: 342,
    featured: true,
    isTrending: true,
    isDealOfTheDay: false,
    isNewArrival: true,
    isBestSeller: true,
    returnPolicyDays: 30,
    warrantyInfo: '1 Year Apple Limited Warranty + Optional AppleCare+',
    shippingWeightKg: 0.42,
    createdAt: '2023-09-22T08:00:00Z',
    updatedAt: '2024-02-14T10:00:00Z',
  },
  {
    id: 'prod-sony-wh1000xm5',
    sellerId: 'seller-tech-vault',
    sellerName: 'TechVault Official',
    title: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    slug: 'sony-wh-1000xm5-wireless-noise-cancelling-headphones',
    shortDescription: 'Industry-leading noise cancellation with two processors and 8 microphones for unparalleled silence and high-res audio.',
    description: `The Sony WH-1000XM5 headphones rewrite the rules for distraction-free listening. Two processors control 8 microphones for unprecedented noise cancellation and exceptional call quality. With a newly developed 30mm driver unit featuring a light and rigid dome using carbon fiber composite material, sound clarity is elevated to audiophile standards.

Enjoy up to 30 hours of battery life with quick charging (3 minutes gives 3 hours playback). Ultra-comfortable, lightweight design finished in soft fit leather.`,
    brand: sonyBrand,
    category: electronicsCategory,
    subCategory: electronicsCategory.subcategories?.[2],
    tags: ['sony', 'headphones', 'noise-cancelling', 'anc', 'wireless', 'bluetooth', 'audio'],
    price: 348.00,
    originalPrice: 399.99,
    discountPercentage: 13,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 64,
    sku: 'SONY-WHXM5-MASTER',
    images: [
      { id: 'img-xm5-1', url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80', altText: 'Sony WH-1000XM5 Black', isPrimary: true, order: 1 },
      { id: 'img-xm5-2', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80', altText: 'Sony WH-1000XM5 Side Angle', isPrimary: false, order: 2 },
    ],
    attributes: [
      {
        id: 'attr-color',
        name: 'Color',
        type: 'color',
        options: [
          { id: 'col-black', name: 'Midnight Black', value: '#111827' },
          { id: 'col-silver', name: 'Platinum Silver', value: '#E5E7EB' },
          { id: 'col-blue', name: 'Midnight Blue', value: '#1E3A8A' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-xm5-blk',
        productId: 'prod-sony-wh1000xm5',
        sku: 'SONY-XM5-BLK',
        title: 'Midnight Black',
        price: 348.00,
        originalPrice: 399.99,
        inventoryQuantity: 34,
        stockStatus: 'in_stock',
        attributes: { Color: 'Midnight Black' },
      },
      {
        id: 'var-xm5-slv',
        productId: 'prod-sony-wh1000xm5',
        sku: 'SONY-XM5-SLV',
        title: 'Platinum Silver',
        price: 348.00,
        originalPrice: 399.99,
        inventoryQuantity: 20,
        stockStatus: 'in_stock',
        attributes: { Color: 'Platinum Silver' },
      },
      {
        id: 'var-xm5-blu',
        productId: 'prod-sony-wh1000xm5',
        sku: 'SONY-XM5-BLU',
        title: 'Midnight Blue',
        price: 348.00,
        originalPrice: 399.99,
        inventoryQuantity: 10,
        stockStatus: 'in_stock',
        attributes: { Color: 'Midnight Blue' },
      },
    ],
    specifications: [
      { group: 'Audio', key: 'Driver Size', value: '30mm Carbon Fiber Composite' },
      { group: 'Audio', key: 'Codecs Supported', value: 'LDAC, AAC, SBC' },
      { group: 'Battery', key: 'Playback Time (ANC on)', value: '30 hours' },
      { group: 'Battery', key: 'Fast Charge', value: '3 min charge = 3 hours playback' },
      { group: 'Connectivity', key: 'Bluetooth', value: 'Bluetooth 5.2 with Multipoint' },
      { group: 'Weight', key: 'Weight', value: '250 grams' },
    ],
    rating: 4.8,
    reviewCount: 284,
    featured: true,
    isTrending: true,
    isDealOfTheDay: true,
    isNewArrival: false,
    isBestSeller: true,
    returnPolicyDays: 30,
    warrantyInfo: '1 Year Manufacturer Warranty',
    shippingWeightKg: 0.65,
    createdAt: '2023-06-10T10:00:00Z',
    updatedAt: '2024-02-12T14:30:00Z',
  },
  {
    id: 'prod-macbook-pro-16',
    sellerId: 'seller-tech-vault',
    sellerName: 'TechVault Official',
    title: 'Apple MacBook Pro 16" - M3 Max',
    slug: 'apple-macbook-pro-16-m3-max',
    shortDescription: 'Unprecedented computing power with 16-core CPU, 40-core GPU, Liquid Retina XDR display, and up to 22 hours of battery life.',
    description: `MacBook Pro blasts forward with the M3 Max chip, an insanely advanced chip that powers massive performance for demanding workflows. With industry-leading battery life — up to 22 hours — and a gorgeous Liquid Retina XDR display with 1600 nits peak brightness, it’s a pro laptop without equal.`,
    brand: appleBrand,
    category: electronicsCategory,
    subCategory: electronicsCategory.subcategories?.[1],
    tags: ['apple', 'macbook', 'm3', 'laptop', 'pro', 'retina', 'workstation'],
    price: 3499.00,
    originalPrice: 3699.00,
    discountPercentage: 5,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 15,
    sku: 'MBP16-M3MAX-MASTER',
    images: [
      { id: 'img-mbp-1', url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80', altText: 'MacBook Pro Space Black', isPrimary: true, order: 1 },
      { id: 'img-mbp-2', url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80', altText: 'MacBook Pro Keyboard and Trackpad', isPrimary: false, order: 2 },
    ],
    attributes: [
      {
        id: 'attr-color',
        name: 'Color',
        type: 'color',
        options: [
          { id: 'col-blk', name: 'Space Black', value: '#1E1E24' },
          { id: 'col-slv', name: 'Silver', value: '#E2E4E9' },
        ],
      },
      {
        id: 'attr-unified-memory',
        name: 'Unified Memory',
        type: 'select',
        options: [
          { id: 'mem-36', name: '36GB Unified Memory', value: '36gb' },
          { id: 'mem-48', name: '48GB Unified Memory', value: '48gb' },
          { id: 'mem-128', name: '128GB Unified Memory', value: '128gb' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-mbp-blk-36',
        productId: 'prod-macbook-pro-16',
        sku: 'MBP16-BLK-36GB',
        title: 'Space Black / 36GB Memory / 1TB SSD',
        price: 3499.00,
        originalPrice: 3699.00,
        inventoryQuantity: 9,
        stockStatus: 'in_stock',
        attributes: { Color: 'Space Black', 'Unified Memory': '36GB Unified Memory' },
      },
      {
        id: 'var-mbp-blk-48',
        productId: 'prod-macbook-pro-16',
        sku: 'MBP16-BLK-48GB',
        title: 'Space Black / 48GB Memory / 1TB SSD',
        price: 3999.00,
        originalPrice: 4199.00,
        inventoryQuantity: 6,
        stockStatus: 'in_stock',
        attributes: { Color: 'Space Black', 'Unified Memory': '48GB Unified Memory' },
      },
    ],
    specifications: [
      { group: 'Processor', key: 'Chip', value: 'Apple M3 Max (16-core CPU, 40-core GPU)' },
      { group: 'Display', key: 'Display Size', value: '16.2-inch Liquid Retina XDR (3456 x 2234)' },
      { group: 'Display', key: 'Peak Brightness', value: '1600 nits XDR / 600 nits SDR' },
      { group: 'Ports', key: 'Thunderbolt', value: '3x Thunderbolt 4 / USB-C, HDMI, SDXC, MagSafe 3' },
      { group: 'Battery', key: 'Battery Capacity', value: '100Wh Lithium-Polymer, up to 22h runtime' },
    ],
    rating: 5.0,
    reviewCount: 96,
    featured: true,
    isTrending: false,
    isDealOfTheDay: false,
    isNewArrival: true,
    isBestSeller: false,
    returnPolicyDays: 30,
    warrantyInfo: '1 Year Apple Limited Warranty',
    shippingWeightKg: 2.16,
    createdAt: '2023-11-07T08:00:00Z',
    updatedAt: '2024-01-20T11:00:00Z',
  },
  {
    id: 'prod-nike-air-jordan-1',
    sellerId: 'seller-aura-lifestyle',
    sellerName: 'Aura Lifestyle & Home',
    title: 'Nike Air Jordan 1 Retro High OG - Chicago Reimagined',
    slug: 'nike-air-jordan-1-retro-high-og-chicago',
    shortDescription: 'The legendary silhouette that started it all, rebuilt with premium cracked leather and vintage aesthetic accents.',
    description: `Clean and classic, the Air Jordan 1 Retro High OG brings back the coveted Chicago colorway with a vintage twist. Premium leather, responsive Air-Sole cushioning, and durable traction combine to deliver timeless streetwear sophistication.`,
    brand: nikeBrand,
    category: fashionCategory,
    subCategory: fashionCategory.subcategories?.[2],
    tags: ['nike', 'sneakers', 'jordan', 'shoes', 'streetwear', 'retro', 'limited-edition'],
    price: 180.00,
    originalPrice: 220.00,
    discountPercentage: 18,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 32,
    sku: 'NIKE-AJ1-CHI-MASTER',
    images: [
      { id: 'img-aj1-1', url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80', altText: 'Air Jordan 1 Chicago Red', isPrimary: true, order: 1 },
      { id: 'img-aj1-2', url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80', altText: 'Air Jordan 1 Pair Profile', isPrimary: false, order: 2 },
    ],
    attributes: [
      {
        id: 'attr-size',
        name: 'Shoe Size (US)',
        type: 'size',
        options: [
          { id: 'sz-8', name: 'US 8', value: 'us-8' },
          { id: 'sz-9', name: 'US 9', value: 'us-9' },
          { id: 'sz-10', name: 'US 10', value: 'us-10' },
          { id: 'sz-11', name: 'US 11', value: 'us-11' },
          { id: 'sz-12', name: 'US 12', value: 'us-12' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-aj1-us9',
        productId: 'prod-nike-air-jordan-1',
        sku: 'AJ1-CHI-US9',
        title: 'Chicago Red / US 9',
        price: 180.00,
        originalPrice: 220.00,
        inventoryQuantity: 12,
        stockStatus: 'in_stock',
        attributes: { 'Shoe Size (US)': 'US 9' },
      },
      {
        id: 'var-aj1-us10',
        productId: 'prod-nike-air-jordan-1',
        sku: 'AJ1-CHI-US10',
        title: 'Chicago Red / US 10',
        price: 180.00,
        originalPrice: 220.00,
        inventoryQuantity: 14,
        stockStatus: 'in_stock',
        attributes: { 'Shoe Size (US)': 'US 10' },
      },
      {
        id: 'var-aj1-us11',
        productId: 'prod-nike-air-jordan-1',
        sku: 'AJ1-CHI-US11',
        title: 'Chicago Red / US 11',
        price: 180.00,
        originalPrice: 220.00,
        inventoryQuantity: 6,
        stockStatus: 'low_stock',
        attributes: { 'Shoe Size (US)': 'US 11' },
      },
    ],
    specifications: [
      { group: 'Materials', key: 'Upper', value: 'Full-grain cracked genuine leather' },
      { group: 'Cushioning', key: 'Midsole', value: 'Encapsulated Air-Sole unit in the heel' },
      { group: 'Traction', key: 'Outsole', value: 'Solid rubber with deep flex grooves' },
      { group: 'Origin', key: 'Style Code', value: 'DZ5485-612' },
    ],
    rating: 4.7,
    reviewCount: 419,
    featured: true,
    isTrending: true,
    isDealOfTheDay: false,
    isNewArrival: false,
    isBestSeller: true,
    returnPolicyDays: 30,
    warrantyInfo: 'Official Nike Authenticity Guaranteed',
    shippingWeightKg: 1.2,
    createdAt: '2023-04-12T09:00:00Z',
    updatedAt: '2024-02-01T15:00:00Z',
  },
  {
    id: 'prod-dyson-airwrap',
    sellerId: 'seller-aura-lifestyle',
    sellerName: 'Aura Lifestyle & Home',
    title: 'Dyson Airwrap Multi-Styler Complete Long',
    slug: 'dyson-airwrap-multi-styler-complete-long',
    shortDescription: 'Curl, shape, smooth, and hide flyaways using the Coanda effect without extreme heat damage.',
    description: `Engineered for multiple hair types and longer lengths. Powered by the Dyson digital motor V9, the Airwrap uses aerodynamic Coanda airflow to style hair without heat damage. Intelligent heat control measures air temperature over 40 times a second to prevent extreme heat damage.`,
    brand: dysonBrand,
    category: beautyCategory,
    subCategory: beautyCategory.subcategories?.[2],
    tags: ['dyson', 'haircare', 'styler', 'beauty', 'curler', 'premium', 'coanda'],
    price: 599.99,
    originalPrice: 649.99,
    discountPercentage: 8,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 22,
    sku: 'DYS-AIRWRAP-LONG',
    images: [
      { id: 'img-dyson-1', url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80', altText: 'Dyson Airwrap Complete Copper', isPrimary: true, order: 1 },
      { id: 'img-dyson-2', url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80', altText: 'Dyson Airwrap Attachments Box', isPrimary: false, order: 2 },
    ],
    attributes: [
      {
        id: 'attr-color',
        name: 'Color',
        type: 'color',
        options: [
          { id: 'col-cop', name: 'Copper / Nickel', value: '#B87333' },
          { id: 'col-blu', name: 'Prussian Blue / Rich Copper', value: '#0F2537' },
          { id: 'col-str', name: 'Strawberry Bronze / Blush Pink', value: '#D88A8A' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-dyson-cop',
        productId: 'prod-dyson-airwrap',
        sku: 'DYS-AW-COP',
        title: 'Copper / Nickel',
        price: 599.99,
        originalPrice: 649.99,
        inventoryQuantity: 12,
        stockStatus: 'in_stock',
        attributes: { Color: 'Copper / Nickel' },
      },
      {
        id: 'var-dyson-blu',
        productId: 'prod-dyson-airwrap',
        sku: 'DYS-AW-BLU',
        title: 'Prussian Blue / Rich Copper',
        price: 599.99,
        originalPrice: 649.99,
        inventoryQuantity: 10,
        stockStatus: 'in_stock',
        attributes: { Color: 'Prussian Blue / Rich Copper' },
      },
    ],
    specifications: [
      { group: 'Performance', key: 'Airflow Rate', value: '13.5 liters/sec' },
      { group: 'Power', key: 'Wattage', value: '1300W' },
      { group: 'Technology', key: 'Heat Control', value: 'Intelligent Glass Bead Thermistor (>40 checks/sec)' },
      { group: 'In The Box', key: 'Attachments', value: 'Coanda smoothing dryer, 30mm/40mm long barrels, firm/soft smoothing brushes, round volumizing brush, storage case' },
    ],
    rating: 4.9,
    reviewCount: 178,
    featured: true,
    isTrending: true,
    isDealOfTheDay: false,
    isNewArrival: false,
    isBestSeller: true,
    returnPolicyDays: 30,
    warrantyInfo: '2 Year Dyson Manufacturer Warranty',
    shippingWeightKg: 2.8,
    createdAt: '2023-08-15T12:00:00Z',
    updatedAt: '2024-02-10T09:00:00Z',
  },
  {
    id: 'prod-bose-ultra-quietcomfort',
    sellerId: 'seller-tech-vault',
    sellerName: 'TechVault Official',
    title: 'Bose QuietComfort Ultra Wireless Earbuds',
    slug: 'bose-quietcomfort-ultra-wireless-earbuds',
    shortDescription: 'Breakthrough spatialized audio for more immersive listening and world-class quiet tailored to your ears.',
    description: `Bose QuietComfort Ultra Earbuds feature revolutionary Bose Immersive Audio that takes what you’re hearing out of your head and places it in front of you. CustomTune technology shapes the sound and noise cancellation precisely to the shape of your ears.`,
    brand: boseBrand,
    category: electronicsCategory,
    subCategory: electronicsCategory.subcategories?.[2],
    tags: ['bose', 'earbuds', 'noise-cancelling', 'spatial-audio', 'bluetooth', 'wireless'],
    price: 249.00,
    originalPrice: 299.00,
    discountPercentage: 17,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 40,
    sku: 'BOSE-QCU-EARBUDS',
    images: [
      { id: 'img-bose-1', url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80', altText: 'Bose QC Ultra Earbuds Case', isPrimary: true, order: 1 },
      { id: 'img-bose-2', url: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800&auto=format&fit=crop&q=80', altText: 'Bose QC Ultra Earbud Detail', isPrimary: false, order: 2 },
    ],
    attributes: [
      {
        id: 'attr-color',
        name: 'Color',
        type: 'color',
        options: [
          { id: 'col-blk', name: 'Triple Black', value: '#0A0A0A' },
          { id: 'col-wht', name: 'White Smoke', value: '#F5F5F7' },
          { id: 'col-blu', name: 'Moonstone Blue', value: '#6B8E9B' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-bose-blk',
        productId: 'prod-bose-ultra-quietcomfort',
        sku: 'BOSE-QC-BLK',
        title: 'Triple Black',
        price: 249.00,
        originalPrice: 299.00,
        inventoryQuantity: 20,
        stockStatus: 'in_stock',
        attributes: { Color: 'Triple Black' },
      },
      {
        id: 'var-bose-wht',
        productId: 'prod-bose-ultra-quietcomfort',
        sku: 'BOSE-QC-WHT',
        title: 'White Smoke',
        price: 249.00,
        originalPrice: 299.00,
        inventoryQuantity: 20,
        stockStatus: 'in_stock',
        attributes: { Color: 'White Smoke' },
      },
    ],
    specifications: [
      { group: 'Audio', key: 'Audio Technology', value: 'Bose Immersive Spatialized Audio + CustomTune' },
      { group: 'Battery', key: 'Earbud Playtime', value: 'Up to 6 hours (up to 4 hours with Immersive Audio)' },
      { group: 'Battery', key: 'Charging Case', value: 'Provides additional 18 hours of charge' },
      { group: 'Durability', key: 'Water Resistance', value: 'IPX4 Sweat and weather resistant' },
    ],
    rating: 4.6,
    reviewCount: 142,
    featured: false,
    isTrending: true,
    isDealOfTheDay: true,
    isNewArrival: true,
    isBestSeller: false,
    returnPolicyDays: 30,
    warrantyInfo: '1 Year Manufacturer Warranty',
    shippingWeightKg: 0.28,
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2024-02-08T12:00:00Z',
  },
  {
    id: 'prod-logitech-g-pro-superlight',
    sellerId: 'seller-tech-vault',
    sellerName: 'TechVault Official',
    title: 'Logitech G PRO X SUPERLIGHT 2 Wireless Gaming Mouse',
    slug: 'logitech-g-pro-x-superlight-2-wireless-gaming-mouse',
    shortDescription: 'The pinnacle of esports precision weighing only 60 grams with LIGHTFORCE hybrid switches and HERO 2 sensor.',
    description: `Designed in collaboration with top esports pros, the PRO X SUPERLIGHT 2 features LIGHTFORCE hybrid optical-mechanical switches, HERO 2 sensor with 32,000 DPI and over 500 IPS tracking, LIGHTSPEED wireless with 2000Hz polling rate, and USB-C fast charging.`,
    brand: logitechBrand,
    category: gamingCategory,
    subCategory: gamingCategory.subcategories?.[1],
    tags: ['logitech', 'gaming', 'mouse', 'esports', 'wireless', 'rgb', 'hero2'],
    price: 159.99,
    originalPrice: 179.99,
    discountPercentage: 11,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 55,
    sku: 'LOGI-GPX2-MASTER',
    images: [
      { id: 'img-logi-1', url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80', altText: 'Logitech G Pro Superlight 2 Top View', isPrimary: true, order: 1 },
      { id: 'img-logi-2', url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80', altText: 'Logitech Gaming Mouse Profile', isPrimary: false, order: 2 },
    ],
    attributes: [
      {
        id: 'attr-color',
        name: 'Color',
        type: 'color',
        options: [
          { id: 'col-blk', name: 'Matte Black', value: '#1C1C1E' },
          { id: 'col-wht', name: 'White', value: '#FFFFFF' },
          { id: 'col-pnk', name: 'Magenta Pink', value: '#E11D48' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-gpx-blk',
        productId: 'prod-logitech-g-pro-superlight',
        sku: 'GPX2-BLK',
        title: 'Matte Black',
        price: 159.99,
        originalPrice: 179.99,
        inventoryQuantity: 25,
        stockStatus: 'in_stock',
        attributes: { Color: 'Matte Black' },
      },
      {
        id: 'var-gpx-wht',
        productId: 'prod-logitech-g-pro-superlight',
        sku: 'GPX2-WHT',
        title: 'White',
        price: 159.99,
        originalPrice: 179.99,
        inventoryQuantity: 20,
        stockStatus: 'in_stock',
        attributes: { Color: 'White' },
      },
      {
        id: 'var-gpx-pnk',
        productId: 'prod-logitech-g-pro-superlight',
        sku: 'GPX2-PNK',
        title: 'Magenta Pink',
        price: 159.99,
        originalPrice: 179.99,
        inventoryQuantity: 10,
        stockStatus: 'in_stock',
        attributes: { Color: 'Magenta Pink' },
      },
    ],
    specifications: [
      { group: 'Sensor', key: 'Sensor Type', value: 'HERO 2 (100 – 32,000 DPI, >500 IPS)' },
      { group: 'Switches', key: 'Main Buttons', value: 'LIGHTFORCE Optical-Mechanical Hybrid Switches' },
      { group: 'Weight', key: 'Weight', value: '60 grams ultra-lightweight' },
      { group: 'Battery', key: 'Runtime', value: 'Up to 95 hours constant motion' },
      { group: 'Connectivity', key: 'Polling Rate', value: '2000Hz LIGHTSPEED Wireless + USB-C' },
    ],
    rating: 4.9,
    reviewCount: 310,
    featured: false,
    isTrending: true,
    isDealOfTheDay: false,
    isNewArrival: false,
    isBestSeller: true,
    returnPolicyDays: 30,
    warrantyInfo: '2 Year Logitech Manufacturer Warranty',
    shippingWeightKg: 0.35,
    createdAt: '2023-09-18T11:00:00Z',
    updatedAt: '2024-02-11T13:00:00Z',
  },
  {
    id: 'prod-scandinavian-oak-dining-table',
    sellerId: 'seller-aura-lifestyle',
    sellerName: 'Aura Lifestyle & Home',
    title: 'Nordic Solid White Oak Dining Table (6-8 Seater)',
    slug: 'nordic-solid-white-oak-dining-table',
    shortDescription: 'Handcrafted from 100% sustainable European white oak with soft organic bevelled edges and a matte protective seal.',
    description: `Bring warmth and modern simplicity to your home with the Nordic Oak Dining Table. Each table is meticulously built from FSC-certified European white oak with distinctive natural grain patterns. The durable matte lacquer finish resists spills and heat while preserving the organic tactile feel of natural timber.`,
    brand: {
      id: 'brand-aura',
      name: 'Aura Home',
      slug: 'aura-home',
      description: 'Scandinavian furniture and architectural homeware.',
      featured: true,
    },
    category: homeCategory,
    subCategory: homeCategory.subcategories?.[0],
    tags: ['furniture', 'dining-table', 'oak', 'scandinavian', 'home-decor', 'solid-wood'],
    price: 899.00,
    originalPrice: 1099.00,
    discountPercentage: 18,
    currency: 'USD',
    status: 'active',
    stockStatus: 'in_stock',
    totalInventory: 14,
    sku: 'AURA-OAK-DT8',
    images: [
      { id: 'img-dt-1', url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80', altText: 'Nordic Oak Table in Modern Room', isPrimary: true, order: 1 },
      { id: 'img-dt-2', url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&auto=format&fit=crop&q=80', altText: 'Solid Wood Grain Close-up', isPrimary: false, order: 2 },
    ],
    attributes: [
      {
        id: 'attr-size',
        name: 'Table Length',
        type: 'select',
        options: [
          { id: 'len-180', name: '180 cm (6 Seater)', value: '180cm' },
          { id: 'len-220', name: '220 cm (8-10 Seater)', value: '220cm' },
        ],
      },
      {
        id: 'attr-finish',
        name: 'Timber Finish',
        type: 'select',
        options: [
          { id: 'fin-nat', name: 'Natural White Oak', value: 'natural-oak' },
          { id: 'fin-smk', name: 'Smoked Walnut Finish', value: 'smoked-walnut' },
        ],
      },
    ],
    variants: [
      {
        id: 'var-dt-180-nat',
        productId: 'prod-scandinavian-oak-dining-table',
        sku: 'OAK-DT-180-NAT',
        title: '180 cm / Natural White Oak',
        price: 899.00,
        originalPrice: 1099.00,
        inventoryQuantity: 8,
        stockStatus: 'in_stock',
        attributes: { 'Table Length': '180 cm (6 Seater)', 'Timber Finish': 'Natural White Oak' },
      },
      {
        id: 'var-dt-220-nat',
        productId: 'prod-scandinavian-oak-dining-table',
        sku: 'OAK-DT-220-NAT',
        title: '220 cm / Natural White Oak',
        price: 1099.00,
        originalPrice: 1299.00,
        inventoryQuantity: 6,
        stockStatus: 'in_stock',
        attributes: { 'Table Length': '220 cm (8-10 Seater)', 'Timber Finish': 'Natural White Oak' },
      },
    ],
    specifications: [
      { group: 'Dimensions', key: 'Height', value: '75 cm (29.5 inches)' },
      { group: 'Dimensions', key: 'Width', value: '95 cm (37.4 inches)' },
      { group: 'Materials', key: 'Construction', value: '100% Solid European White Oak (FSC Certified)' },
      { group: 'Assembly', key: 'Assembly Required', value: 'Yes, legs attach with included hex bolts (15 mins)' },
      { group: 'Care', key: 'Cleaning', value: 'Wipe clean with a damp cloth; treat with wood oil annually' },
    ],
    rating: 4.9,
    reviewCount: 58,
    featured: true,
    isTrending: false,
    isDealOfTheDay: false,
    isNewArrival: true,
    isBestSeller: false,
    returnPolicyDays: 45,
    warrantyInfo: '5 Year Structural Craftsmanship Warranty',
    shippingWeightKg: 42.0,
    createdAt: '2023-11-20T10:00:00Z',
    updatedAt: '2024-02-05T16:00:00Z',
  },
];
