import { ProductReview } from '../types';

export const MOCK_REVIEWS: ProductReview[] = [
  {
    id: 'rev-1',
    productId: 'prod-iphone-15-pro',
    productTitle: 'Apple iPhone 15 Pro Max - Titanium',
    userId: 'user-cust-101',
    userName: 'David K.',
    userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'The weight difference is unbelievable! Best camera yet.',
    comment: 'Moving from the 13 Pro Max to the 15 Pro Max in Natural Titanium was night and day. The contoured edges make it so much more comfortable to hold for hours. The 5x telephoto lens produces stunning portraits with natural depth of field.',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    ],
    isVerifiedPurchase: true,
    helpfulCount: 42,
    unhelpfulCount: 1,
    status: 'published',
    sellerReply: {
      id: 'rep-1',
      authorId: 'user-seller-1',
      authorName: 'TechVault Official',
      authorRole: 'seller',
      content: 'Thank you so much David! We are thrilled you love the Natural Titanium finish and camera optics. Enjoy your new flagship device!',
      createdAt: '2023-10-02T14:30:00Z',
    },
    createdAt: '2023-09-30T11:15:00Z',
    updatedAt: '2023-09-30T11:15:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-iphone-15-pro',
    productTitle: 'Apple iPhone 15 Pro Max - Titanium',
    userId: 'user-cust-102',
    userName: 'Elena Rostova',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'USB-C and Action button are game changers for creators.',
    comment: 'Connecting external SSDs directly via USB-C to record ProRes 4K 60fps video directly to the drive makes this a genuine mobile cinema rig. Battery life effortlessly lasts me through a full shooting day.',
    images: [],
    isVerifiedPurchase: true,
    helpfulCount: 29,
    unhelpfulCount: 0,
    status: 'published',
    createdAt: '2023-10-15T18:22:00Z',
    updatedAt: '2023-10-15T18:22:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-sony-wh1000xm5',
    productTitle: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    userId: 'user-cust-103',
    userName: 'Marcus Chen',
    userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Absolute silence on transatlantic flights.',
    comment: 'The ANC on the XM5 completely deletes jet engine drone. Call quality in windy conditions or noisy coffee shops is vastly improved over the XM4. Soft leather cups do not create pressure hotspots.',
    images: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop&q=80',
    ],
    isVerifiedPurchase: true,
    helpfulCount: 56,
    unhelpfulCount: 2,
    status: 'published',
    createdAt: '2023-08-20T09:40:00Z',
    updatedAt: '2023-08-20T09:40:00Z',
  },
];
