import { SellerProfile } from '../types';

export const MOCK_SELLERS: SellerProfile[] = [
  {
    id: 'seller-tech-vault',
    userId: 'user-seller-1',
    storeName: 'TechVault Official',
    storeSlug: 'techvault-official',
    tagline: 'Authorized Distributor of Flagship Electronics & Audio',
    description: 'Providing genuine consumer electronics with manufacturer warranties and 24/7 express dispatch.',
    logoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    email: 'contact@techvault.com',
    phone: '+1 (555) 234-8901',
    businessRegistrationNumber: 'US-REG-892134-T',
    taxIdentificationNumber: 'TAX-9982314-US',
    status: 'active',
    tier: 'platinum',
    commissionRate: 8.0,
    rating: 4.9,
    totalSales: 489200,
    totalOrders: 1420,
    productCount: 28,
    joinedDate: '2023-01-15T00:00:00Z',
    address: {
      id: 'addr-seller-1',
      fullName: 'TechVault Logistics LLC',
      phone: '+1 (555) 234-8901',
      street: '742 Evergreen Silicon Way',
      city: 'San Jose',
      state: 'CA',
      postalCode: '95134',
      country: 'United States',
    },
    bankDetails: {
      accountHolder: 'TechVault LLC',
      bankName: 'Silicon Valley Commercial Bank',
      accountNumber: '**** **** 4891',
      routingNumber: '121000358',
      accountType: 'checking',
    },
    policies: {
      shippingPolicy: 'Same-day shipping for orders placed before 2:00 PM PST. Express carrier delivery in 2-3 business days.',
      returnPolicy: '30-day hassle-free return guarantee for unopened or defective products with pre-paid return labels.',
      warrantyPolicy: '1-year official brand warranty with direct replacement within the first 60 days.',
    },
  },
  {
    id: 'seller-aura-lifestyle',
    userId: 'user-seller-2',
    storeName: 'Aura Lifestyle & Home',
    storeSlug: 'aura-lifestyle',
    tagline: 'Curated Scandinavian Decor, Ergonomic Furniture & Cookware',
    description: 'Transforming everyday spaces with timeless minimalist aesthetics and eco-friendly sustainable materials.',
    logoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
    email: 'support@auralifestyle.com',
    phone: '+1 (555) 782-9912',
    businessRegistrationNumber: 'US-REG-443219-A',
    taxIdentificationNumber: 'TAX-7729104-US',
    status: 'active',
    tier: 'gold',
    commissionRate: 9.5,
    rating: 4.8,
    totalSales: 215400,
    totalOrders: 890,
    productCount: 19,
    joinedDate: '2023-05-20T00:00:00Z',
    address: {
      id: 'addr-seller-2',
      fullName: 'Aura Design Studios',
      phone: '+1 (555) 782-9912',
      street: '108 Grand River Ave',
      city: 'Portland',
      state: 'OR',
      postalCode: '97201',
      country: 'United States',
    },
    bankDetails: {
      accountHolder: 'Aura Lifestyle Co.',
      bankName: 'Pacific Northwest Bank',
      accountNumber: '**** **** 9012',
      routingNumber: '325070760',
      accountType: 'checking',
    },
    policies: {
      shippingPolicy: 'Shipped via carbon-neutral ground transport in 3-5 business days.',
      returnPolicy: '45-day home trial with free return shipping on all furniture items.',
      warrantyPolicy: '5-year structural warranty on all solid wood craftsmanship.',
    },
  },
];
