-- Migration: 0045_create_review_helpful_votes_table.sql
-- ShopSphere Enterprise Database Migration

CREATE TABLE IF NOT EXISTS review_helpful_votes (
  id VARCHAR(64) PRIMARY KEY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  version INT DEFAULT 1 NOT NULL,
  field_1_str VARCHAR(255) DEFAULT NULL,
  field_1_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_1_int INT DEFAULT 0,
  field_1_bool BOOLEAN DEFAULT FALSE,
  field_1_json JSONB DEFAULT '{}'::jsonb,
  field_2_str VARCHAR(255) DEFAULT NULL,
  field_2_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_2_int INT DEFAULT 0,
  field_2_bool BOOLEAN DEFAULT FALSE,
  field_2_json JSONB DEFAULT '{}'::jsonb,
  field_3_str VARCHAR(255) DEFAULT NULL,
  field_3_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_3_int INT DEFAULT 0,
  field_3_bool BOOLEAN DEFAULT FALSE,
  field_3_json JSONB DEFAULT '{}'::jsonb,
  field_4_str VARCHAR(255) DEFAULT NULL,
  field_4_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_4_int INT DEFAULT 0,
  field_4_bool BOOLEAN DEFAULT FALSE,
  field_4_json JSONB DEFAULT '{}'::jsonb,
  field_5_str VARCHAR(255) DEFAULT NULL,
  field_5_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_5_int INT DEFAULT 0,
  field_5_bool BOOLEAN DEFAULT FALSE,
  field_5_json JSONB DEFAULT '{}'::jsonb,
  field_6_str VARCHAR(255) DEFAULT NULL,
  field_6_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_6_int INT DEFAULT 0,
  field_6_bool BOOLEAN DEFAULT FALSE,
  field_6_json JSONB DEFAULT '{}'::jsonb,
  field_7_str VARCHAR(255) DEFAULT NULL,
  field_7_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_7_int INT DEFAULT 0,
  field_7_bool BOOLEAN DEFAULT FALSE,
  field_7_json JSONB DEFAULT '{}'::jsonb,
  field_8_str VARCHAR(255) DEFAULT NULL,
  field_8_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_8_int INT DEFAULT 0,
  field_8_bool BOOLEAN DEFAULT FALSE,
  field_8_json JSONB DEFAULT '{}'::jsonb,
  field_9_str VARCHAR(255) DEFAULT NULL,
  field_9_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_9_int INT DEFAULT 0,
  field_9_bool BOOLEAN DEFAULT FALSE,
  field_9_json JSONB DEFAULT '{}'::jsonb,
  field_10_str VARCHAR(255) DEFAULT NULL,
  field_10_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_10_int INT DEFAULT 0,
  field_10_bool BOOLEAN DEFAULT FALSE,
  field_10_json JSONB DEFAULT '{}'::jsonb,
  field_11_str VARCHAR(255) DEFAULT NULL,
  field_11_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_11_int INT DEFAULT 0,
  field_11_bool BOOLEAN DEFAULT FALSE,
  field_11_json JSONB DEFAULT '{}'::jsonb,
  field_12_str VARCHAR(255) DEFAULT NULL,
  field_12_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_12_int INT DEFAULT 0,
  field_12_bool BOOLEAN DEFAULT FALSE,
  field_12_json JSONB DEFAULT '{}'::jsonb,
  field_13_str VARCHAR(255) DEFAULT NULL,
  field_13_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_13_int INT DEFAULT 0,
  field_13_bool BOOLEAN DEFAULT FALSE,
  field_13_json JSONB DEFAULT '{}'::jsonb,
  field_14_str VARCHAR(255) DEFAULT NULL,
  field_14_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_14_int INT DEFAULT 0,
  field_14_bool BOOLEAN DEFAULT FALSE,
  field_14_json JSONB DEFAULT '{}'::jsonb,
  field_15_str VARCHAR(255) DEFAULT NULL,
  field_15_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_15_int INT DEFAULT 0,
  field_15_bool BOOLEAN DEFAULT FALSE,
  field_15_json JSONB DEFAULT '{}'::jsonb,
  field_16_str VARCHAR(255) DEFAULT NULL,
  field_16_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_16_int INT DEFAULT 0,
  field_16_bool BOOLEAN DEFAULT FALSE,
  field_16_json JSONB DEFAULT '{}'::jsonb,
  field_17_str VARCHAR(255) DEFAULT NULL,
  field_17_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_17_int INT DEFAULT 0,
  field_17_bool BOOLEAN DEFAULT FALSE,
  field_17_json JSONB DEFAULT '{}'::jsonb,
  field_18_str VARCHAR(255) DEFAULT NULL,
  field_18_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_18_int INT DEFAULT 0,
  field_18_bool BOOLEAN DEFAULT FALSE,
  field_18_json JSONB DEFAULT '{}'::jsonb,
  field_19_str VARCHAR(255) DEFAULT NULL,
  field_19_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_19_int INT DEFAULT 0,
  field_19_bool BOOLEAN DEFAULT FALSE,
  field_19_json JSONB DEFAULT '{}'::jsonb,
  field_20_str VARCHAR(255) DEFAULT NULL,
  field_20_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_20_int INT DEFAULT 0,
  field_20_bool BOOLEAN DEFAULT FALSE,
  field_20_json JSONB DEFAULT '{}'::jsonb,
  field_21_str VARCHAR(255) DEFAULT NULL,
  field_21_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_21_int INT DEFAULT 0,
  field_21_bool BOOLEAN DEFAULT FALSE,
  field_21_json JSONB DEFAULT '{}'::jsonb,
  field_22_str VARCHAR(255) DEFAULT NULL,
  field_22_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_22_int INT DEFAULT 0,
  field_22_bool BOOLEAN DEFAULT FALSE,
  field_22_json JSONB DEFAULT '{}'::jsonb,
  field_23_str VARCHAR(255) DEFAULT NULL,
  field_23_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_23_int INT DEFAULT 0,
  field_23_bool BOOLEAN DEFAULT FALSE,
  field_23_json JSONB DEFAULT '{}'::jsonb,
  field_24_str VARCHAR(255) DEFAULT NULL,
  field_24_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_24_int INT DEFAULT 0,
  field_24_bool BOOLEAN DEFAULT FALSE,
  field_24_json JSONB DEFAULT '{}'::jsonb,
  field_25_str VARCHAR(255) DEFAULT NULL,
  field_25_num NUMERIC(12, 4) DEFAULT 0.0000,
  field_25_int INT DEFAULT 0,
  field_25_bool BOOLEAN DEFAULT FALSE,
  field_25_json JSONB DEFAULT '{}'::jsonb,
  metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_created_at ON review_helpful_votes (created_at);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_updated_at ON review_helpful_votes (updated_at);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_is_deleted ON review_helpful_votes (is_deleted);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_1 ON review_helpful_votes (field_1_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_2 ON review_helpful_votes (field_2_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_3 ON review_helpful_votes (field_3_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_4 ON review_helpful_votes (field_4_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_5 ON review_helpful_votes (field_5_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_6 ON review_helpful_votes (field_6_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_7 ON review_helpful_votes (field_7_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_8 ON review_helpful_votes (field_8_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_9 ON review_helpful_votes (field_9_str);
CREATE INDEX IF NOT EXISTS idx_review_helpful_votes_field_10 ON review_helpful_votes (field_10_str);

-- End of migration for review_helpful_votes
