export * from './runner.js';
export * from './migration_lock.js';
export * from './migration_dry_run.js';
export * from './migration_snapshot.js';
export * from './001_create_auth_tables.js';
export * from './002_create_catalog_tables.js';
export * from './003_create_inventory_cart_tables.js';
export * from './004_create_order_payment_tables.js';
export * from './005_create_engagement_tables.js';
export * from './006_create_audit_tables.js';
export * from './007_create_indexes_and_constraints.js';
export * from './008_create_partitioned_tables.js';
export * from './009_create_database_views.js';
export * from './010_create_triggers.js';
export * from './011_create_extended_auth_tables.js';
export * from './012_create_extended_seller_tables.js';
export * from './013_create_extended_catalog_tables.js';
export * from './014_create_extended_inventory_tables.js';
export * from './015_create_extended_order_tables.js';
export * from './016_create_extended_payment_tables.js';
export * from './017_create_extended_engagement_tables.js';
export * from './018_create_extended_notification_tables.js';
export * from './019_create_extended_audit_tables.js';
export * from './020_create_extended_indexes_and_views.js';

import { MigrationRunner } from './runner.js';
import { Migration001CreateAuthTables } from './001_create_auth_tables.js';
import { Migration002CreateCatalogTables } from './002_create_catalog_tables.js';
import { Migration003CreateInventoryCartTables } from './003_create_inventory_cart_tables.js';
import { Migration004CreateOrderPaymentTables } from './004_create_order_payment_tables.js';
import { Migration005CreateEngagementTables } from './005_create_engagement_tables.js';
import { Migration006CreateAuditTables } from './006_create_audit_tables.js';
import { Migration007CreateIndexesAndConstraints } from './007_create_indexes_and_constraints.js';
import { Migration008CreatePartitionedTables } from './008_create_partitioned_tables.js';
import { Migration009CreateDatabaseViews } from './009_create_database_views.js';
import { Migration010CreateTriggers } from './010_create_triggers.js';
import { Migration011CreateExtendedAuthTables } from './011_create_extended_auth_tables.js';
import { Migration012CreateExtendedSellerTables } from './012_create_extended_seller_tables.js';
import { Migration013CreateExtendedCatalogTables } from './013_create_extended_catalog_tables.js';
import { Migration014CreateExtendedInventoryTables } from './014_create_extended_inventory_tables.js';
import { Migration015CreateExtendedOrderTables } from './015_create_extended_order_tables.js';
import { Migration016CreateExtendedPaymentTables } from './016_create_extended_payment_tables.js';
import { Migration017CreateExtendedEngagementTables } from './017_create_extended_engagement_tables.js';
import { Migration018CreateExtendedNotificationTables } from './018_create_extended_notification_tables.js';
import { Migration019CreateExtendedAuditTables } from './019_create_extended_audit_tables.js';
import { Migration020CreateExtendedIndexesAndViews } from './020_create_extended_indexes_and_views.js';
import { Migration021CreateWmsAndLogisticsTables } from './021_create_wms_and_logistics_tables.js';
import { Migration022CreateGeneralLedgerTables } from './022_create_general_ledger_tables.js';
import { Migration023CreateB2BWholesaleTables } from './023_create_b2b_wholesale_tables.js';

export function createDefaultMigrationRunner(dbAdapter: any): MigrationRunner {
  const runner = new MigrationRunner(dbAdapter);
  runner.register(Migration001CreateAuthTables);
  runner.register(Migration002CreateCatalogTables);
  runner.register(Migration003CreateInventoryCartTables);
  runner.register(Migration004CreateOrderPaymentTables);
  runner.register(Migration005CreateEngagementTables);
  runner.register(Migration006CreateAuditTables);
  runner.register(Migration007CreateIndexesAndConstraints);
  runner.register(Migration008CreatePartitionedTables);
  runner.register(Migration009CreateDatabaseViews);
  runner.register(Migration010CreateTriggers);
  runner.register(Migration011CreateExtendedAuthTables);
  runner.register(Migration012CreateExtendedSellerTables);
  runner.register(Migration013CreateExtendedCatalogTables);
  runner.register(Migration014CreateExtendedInventoryTables);
  runner.register(Migration015CreateExtendedOrderTables);
  runner.register(Migration016CreateExtendedPaymentTables);
  runner.register(Migration017CreateExtendedEngagementTables);
  runner.register(Migration018CreateExtendedNotificationTables);
  runner.register(Migration019CreateExtendedAuditTables);
  runner.register(Migration020CreateExtendedIndexesAndViews);
  runner.register(Migration021CreateWmsAndLogisticsTables);
  runner.register(Migration022CreateGeneralLedgerTables);
  runner.register(Migration023CreateB2BWholesaleTables);
  return runner;
}

export * from './021_create_wms_and_logistics_tables.js';

export * from './022_create_general_ledger_tables.js';

export * from './023_create_b2b_wholesale_tables.js';
