/**
 * System Constants, Enums, and Definitions
 * Member 2 - Phase 1: Backend Foundation + Authentication + Users
 */

export const HttpStatus = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export type HttpStatusCode = typeof HttpStatus[keyof typeof HttpStatus];

export const ErrorCode = {
  // Foundation & Generic Errors
  INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  VALIDATION_ERROR: 'REQ_VALIDATION_ERROR',
  INVALID_INPUT: 'REQ_INVALID_INPUT',
  NOT_FOUND: 'RES_NOT_FOUND',
  CONFLICT: 'RES_CONFLICT',
  METHOD_NOT_ALLOWED: 'REQ_METHOD_NOT_ALLOWED',
  RATE_LIMIT_EXCEEDED: 'SEC_RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SYS_SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DB_OPERATION_ERROR',

  // Authentication Errors
  AUTHENTICATION_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'AUTH_USERNAME_ALREADY_EXISTS',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  TOKEN_REUSED: 'AUTH_TOKEN_REUSED_BREACH',
  INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  SESSION_REVOKED: 'AUTH_SESSION_REVOKED',

  // Password Errors
  PASSWORD_TOO_WEAK: 'PWD_TOO_WEAK',
  PASSWORD_TOO_SHORT: 'PWD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PWD_TOO_LONG',
  PASSWORD_REQUIRES_UPPERCASE: 'PWD_REQUIRES_UPPERCASE',
  PASSWORD_REQUIRES_LOWERCASE: 'PWD_REQUIRES_LOWERCASE',
  PASSWORD_REQUIRES_NUMBER: 'PWD_REQUIRES_NUMBER',
  PASSWORD_REQUIRES_SYMBOL: 'PWD_REQUIRES_SYMBOL',
  PASSWORD_COMMON_DICTIONARY: 'PWD_COMMON_DICTIONARY',
  PASSWORD_MATCHES_USERNAME: 'PWD_MATCHES_USERNAME',
  PASSWORD_MATCHES_EMAIL: 'PWD_MATCHES_EMAIL',
  PASSWORD_REUSED: 'PWD_PREVIOUSLY_USED',
  CURRENT_PASSWORD_INVALID: 'PWD_CURRENT_INVALID',
  PASSWORD_RESET_TOKEN_INVALID: 'PWD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PWD_RESET_TOKEN_EXPIRED',
  PASSWORD_RESET_TOKEN_USED: 'PWD_RESET_TOKEN_USED',

  // Authorization & RBAC Errors
  FORBIDDEN: 'RBAC_ACCESS_DENIED',
  INSUFFICIENT_PERMISSIONS: 'RBAC_INSUFFICIENT_PERMISSIONS',
  INVALID_ROLE: 'RBAC_INVALID_ROLE',
  ROLE_ESCALATION_DENIED: 'RBAC_ROLE_ESCALATION_DENIED',
  UNAUTHORIZED_RESOURCE_ACCESS: 'RBAC_RESOURCE_ACCESS_DENIED',

  // User Profile & Address Errors
  PROFILE_UPDATE_FAILED: 'USR_PROFILE_UPDATE_FAILED',
  ADDRESS_NOT_FOUND: 'ADDR_NOT_FOUND',
  ADDRESS_ACCESS_DENIED: 'ADDR_ACCESS_DENIED',
  ADDRESS_LIMIT_EXCEEDED: 'ADDR_LIMIT_EXCEEDED',
  INVALID_POSTAL_CODE: 'ADDR_INVALID_POSTAL_CODE',
  INVALID_COUNTRY_CODE: 'ADDR_INVALID_COUNTRY_CODE',
  PREFERENCES_NOT_FOUND: 'PREF_NOT_FOUND',
  PREFERENCES_UPDATE_FAILED: 'PREF_UPDATE_FAILED',
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];

export const Roles = {
  CUSTOMER: 'CUSTOMER',
  SELLER: 'SELLER',
  ADMIN: 'ADMIN',
} as const;

export type Role = typeof Roles[keyof typeof Roles];

export const AccountStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
} as const;

export type AccountStatusType = typeof AccountStatus[keyof typeof AccountStatus];

export const TokenType = {
  ACCESS: 'ACCESS',
  REFRESH: 'REFRESH',
  PASSWORD_RESET: 'PASSWORD_RESET',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
} as const;

export type TokenTypeEnum = typeof TokenType[keyof typeof TokenType];

export const AddressType = {
  SHIPPING: 'SHIPPING',
  BILLING: 'BILLING',
  HOME: 'HOME',
  WORK: 'WORK',
  OTHER: 'OTHER',
} as const;

export type AddressTypeEnum = typeof AddressType[keyof typeof AddressType];

export const SystemHeaders = {
  REQUEST_ID: 'x-request-id',
  CORRELATION_ID: 'x-correlation-id',
  API_VERSION: 'x-api-version',
  RESPONSE_TIME: 'x-response-time',
  RATE_LIMIT_LIMIT: 'ratelimit-limit',
  RATE_LIMIT_REMAINING: 'ratelimit-remaining',
  RATE_LIMIT_RESET: 'ratelimit-reset',
  RETRY_AFTER: 'retry-after',
} as const;

export const Permissions = {
  // User permissions
  USERS_READ_SELF: 'users:read:self',
  USERS_WRITE_SELF: 'users:write:self',
  USERS_DELETE_SELF: 'users:delete:self',
  USERS_READ_ALL: 'users:read:all',
  USERS_WRITE_ALL: 'users:write:all',
  USERS_UPDATE_STATUS: 'users:update:status',
  USERS_DELETE_ALL: 'users:delete:all',

  // Address permissions
  ADDRESSES_CREATE_SELF: 'addresses:create:self',
  ADDRESSES_READ_SELF: 'addresses:read:self',
  ADDRESSES_UPDATE_SELF: 'addresses:update:self',
  ADDRESSES_DELETE_SELF: 'addresses:delete:self',
  ADDRESSES_READ_ALL: 'addresses:read:all',
  ADDRESSES_WRITE_ALL: 'addresses:write:all',

  // Auth & Session permissions
  AUTH_REFRESH_TOKEN: 'auth:refresh',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_CHANGE_PASSWORD: 'auth:change_password',
  AUTH_SESSIONS_READ_SELF: 'auth:sessions:read:self',
  AUTH_SESSIONS_REVOKE_SELF: 'auth:sessions:revoke:self',
  AUTH_SESSIONS_READ_ALL: 'auth:sessions:read:all',
  AUTH_SESSIONS_REVOKE_ALL: 'auth:sessions:revoke:all',

  // Preferences permissions
  PREFERENCES_READ_SELF: 'preferences:read:self',
  PREFERENCES_WRITE_SELF: 'preferences:write:self',

  // Admin and System permissions
  SYSTEM_AUDIT_READ: 'system:audit:read',
  SYSTEM_METRICS_READ: 'system:metrics:read',
  ADMIN_FULL_ACCESS: 'admin:*',
} as const;

export type Permission = typeof Permissions[keyof typeof Permissions];

export const AuditAction = {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  USER_TOKEN_REFRESH: 'USER_TOKEN_REFRESH',
  USER_PASSWORD_CHANGE: 'USER_PASSWORD_CHANGE',
  USER_PASSWORD_RESET_REQUEST: 'USER_PASSWORD_RESET_REQUEST',
  USER_PASSWORD_RESET_SUCCESS: 'USER_PASSWORD_RESET_SUCCESS',
  USER_PROFILE_UPDATE: 'USER_PROFILE_UPDATE',
  USER_STATUS_UPDATE: 'USER_STATUS_UPDATE',
  USER_ADDRESS_CREATE: 'USER_ADDRESS_CREATE',
  USER_ADDRESS_UPDATE: 'USER_ADDRESS_UPDATE',
  USER_ADDRESS_DELETE: 'USER_ADDRESS_DELETE',
  USER_ADDRESS_SET_DEFAULT: 'USER_ADDRESS_SET_DEFAULT',
  USER_PREFERENCES_UPDATE: 'USER_PREFERENCES_UPDATE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  SECURITY_TOKEN_REUSE_DETECTED: 'SECURITY_TOKEN_REUSE_DETECTED',
} as const;

export type AuditActionType = typeof AuditAction[keyof typeof AuditAction];
