export * from './general_ledger.schema.js';
export * from './wms_warehouse_extended.schema.js';
export * from './types.js';
export * from './user.schema.js';
export * from './role_permission.schema.js';
export * from './seller.schema.js';
export * from './category_brand.schema.js';
export * from './product.schema.js';
export * from './variant_inventory.schema.js';
export * from './cart.schema.js';
export * from './wishlist.schema.js';
export * from './order.schema.js';
export * from './payment.schema.js';
export * from './coupon.schema.js';
export * from './review.schema.js';
export * from './address.schema.js';
export * from './notification.schema.js';
export * from './audit_log.schema.js';
export * from './schema_comparator.js';
export * from './partition_manager.js';
export * from './view_definitions.js';
export * from './trigger_definitions.js';
export * from './schema_graph_validator.js';
export * from './index_advisor.js';

// Extended Enterprise Schemas
export * from './auth_extended.schema.js';
export * from './seller_extended.schema.js';
export * from './catalog_extended.schema.js';
export * from './inventory_extended.schema.js';
export * from './order_extended.schema.js';
export * from './payment_extended.schema.js';
export * from './engagement_extended.schema.js';
export * from './notification_extended.schema.js';
export * from './audit_extended.schema.js';

// Schema Engines & Generators
export * from './mysql_ddl_generator.js';
export * from './temporal_table_manager.js';
export * from './schema_validator.js';

import { SchemaRegistry, TableSchema, ColumnDefinition } from './types.js';

/**
 * SQL DDL Generator for producing valid ANSI SQL / PostgreSQL / SQLite schemas
 */
export class DDLGenerator {
  public static generateCreateTableSQL(schema: TableSchema, dialect: 'postgres' | 'sqlite' = 'postgres'): string {
    const lines: string[] = [];

    for (const [colName, col] of Object.entries(schema.columns)) {
      lines.push(`  ${this.formatColumnDefinition(col, dialect)}`);
    }

    if (schema.primaryKey.length > 0) {
      lines.push(`  CONSTRAINT pk_${schema.tableName} PRIMARY KEY (${schema.primaryKey.join(', ')})`);
    }

    for (const fk of schema.foreignKeys) {
      const fkName = fk.name || `fk_${schema.tableName}_${fk.columnName}`;
      let fkDef = `  CONSTRAINT ${fkName} FOREIGN KEY (${fk.columnName}) REFERENCES ${fk.referencedTable} (${fk.referencedColumn})`;
      if (fk.onDelete) fkDef += ` ON DELETE ${fk.onDelete}`;
      if (fk.onUpdate) fkDef += ` ON UPDATE ${fk.onUpdate}`;
      lines.push(fkDef);
    }

    for (const chk of schema.checks) {
      lines.push(`  CONSTRAINT ${chk.name} CHECK (${chk.expression})`);
    }

    const tableSQL = `CREATE TABLE IF NOT EXISTS ${schema.tableName} (\n${lines.join(',\n')}\n);`;
    return tableSQL;
  }

  public static generateIndexSQL(schema: TableSchema): string[] {
    const stmts: string[] = [];
    for (const idx of schema.indexes) {
      const unique = idx.isUnique ? 'UNIQUE ' : '';
      let sql = `CREATE ${unique}INDEX IF NOT EXISTS ${idx.name} ON ${schema.tableName} (${idx.columns.join(', ')})`;
      if (idx.wherePredicate) {
        sql += ` WHERE ${idx.wherePredicate}`;
      }
      sql += ';';
      stmts.push(sql);
    }
    return stmts;
  }

  public static generateAllDDL(dialect: 'postgres' | 'sqlite' = 'postgres'): string {
    const tables = SchemaRegistry.getAll();
    const orderedNames = SchemaRegistry.getDependencyOrder();
    const orderedSchemas = orderedNames.map((name) => SchemaRegistry.get(name)!).filter(Boolean);

    let script = `-- ========================================================\n`;
    script += `-- ShopSphere Database Schema DDL (Dialect: ${dialect.toUpperCase()})\n`;
    script += `-- Auto-generated by Member 3 Database Engine\n`;
    script += `-- ========================================================\n\n`;

    for (const schema of orderedSchemas) {
      script += `-- Table: ${schema.tableName} (${schema.description})\n`;
      script += this.generateCreateTableSQL(schema, dialect) + '\n\n';

      const indexes = this.generateIndexSQL(schema);
      if (indexes.length > 0) {
        script += indexes.join('\n') + '\n\n';
      }
    }

    return script;
  }

  private static formatColumnDefinition(col: ColumnDefinition, dialect: 'postgres' | 'sqlite'): string {
    let typeStr: string = col.type;
    if (dialect === 'sqlite') {
      switch (col.type) {
        case 'UUID':
        case 'VARCHAR':
        case 'TEXT':
        case 'TIMESTAMP':
        case 'DATE':
        case 'ARRAY':
          typeStr = 'TEXT';
          break;
        case 'INTEGER':
        case 'BIGINT':
        case 'BOOLEAN':
          typeStr = 'INTEGER';
          break;
        case 'DECIMAL':
          typeStr = 'REAL';
          break;
        case 'JSON':
        case 'JSONB':
          typeStr = 'TEXT';
          break;
      }
    } else {
      switch (col.type) {
        case 'UUID':
          typeStr = 'UUID';
          break;
        case 'VARCHAR':
          typeStr = col.length ? `VARCHAR(${col.length})` : 'VARCHAR(255)';
          break;
        case 'DECIMAL':
          typeStr = `DECIMAL(${col.precision || 12}, ${col.scale || 2})`;
          break;
        case 'ARRAY':
          typeStr = 'TEXT[]';
          break;
        case 'JSONB':
          typeStr = 'JSONB';
          break;
        case 'JSON':
          typeStr = 'JSON';
          break;
      }
    }

    let out = `${col.name} ${typeStr}`;
    if (col.isNullable === false) {
      out += ' NOT NULL';
    }
    if (col.defaultValue !== undefined) {
      if (typeof col.defaultValue === 'string' && col.defaultValue.startsWith('CURRENT_')) {
        out += ` DEFAULT ${col.defaultValue}`;
      } else if (typeof col.defaultValue === 'string') {
        out += ` DEFAULT '${col.defaultValue}'`;
      } else if (typeof col.defaultValue === 'number' || typeof col.defaultValue === 'boolean') {
        out += ` DEFAULT ${col.defaultValue}`;
      } else if (typeof col.defaultValue === 'object') {
        out += dialect === 'sqlite' ? ` DEFAULT '${JSON.stringify(col.defaultValue)}'` : ` DEFAULT '${JSON.stringify(col.defaultValue)}'::jsonb`;
      }
    }

    return out;
  }
}
