/**
 * ShopSphere Database Schema - MySQL 8.0 Enterprise DDL Generator
 * Generates production-ready DDL statements with ENGINE=InnoDB, ROW_FORMAT=DYNAMIC, UTF8MB4 charset,
 * optimized composite indexes, foreign key actions, and JSON check constraints.
 */

import { TableSchema, ColumnDefinition } from './types.js';

export class MySqlDdlGenerator {
  /**
   * Generates a CREATE TABLE DDL statement for MySQL 8.0
   */
  public static generateCreateTable(schema: TableSchema): string {
    const lines: string[] = [];

    // Column definitions
    for (const [colName, col] of Object.entries(schema.columns)) {
      lines.push(`  ${this.formatColumnDefinition(colName, col)}`);
    }

    // Primary Key constraint
    if (schema.primaryKey && schema.primaryKey.length > 0) {
      const pkCols = schema.primaryKey.map(col => `\`${col}\``).join(', ');
      lines.push(`  CONSTRAINT \`pk_${schema.tableName}\` PRIMARY KEY (${pkCols})`);
    }

    // Indexes & Unique Constraints
    if (schema.indexes) {
      for (const idx of schema.indexes) {
        const idxCols = idx.columns.map(c => `\`${c}\``).join(', ');
        if (idx.isUnique) {
          lines.push(`  CONSTRAINT \`${idx.name}\` UNIQUE (${idxCols})`);
        } else {
          lines.push(`  INDEX \`${idx.name}\` (${idxCols})`);
        }
      }
    }

    // Foreign Key constraints
    if (schema.foreignKeys) {
      for (const fk of schema.foreignKeys) {
        const onDelete = fk.onDelete ? ` ON DELETE ${fk.onDelete}` : ' ON DELETE RESTRICT';
        const onUpdate = fk.onUpdate ? ` ON UPDATE ${fk.onUpdate}` : ' ON UPDATE CASCADE';
        lines.push(
          `  CONSTRAINT \`fk_${schema.tableName}_${fk.columnName}\` FOREIGN KEY (\`${fk.columnName}\`) ` +
          `REFERENCES \`${fk.referencedTable}\` (\`${fk.referencedColumn}\`)${onDelete}${onUpdate}`
        );
      }
    }

    // Check constraints
    if (schema.checks) {
      for (const chk of schema.checks) {
        lines.push(`  CONSTRAINT \`${chk.name}\` CHECK (${chk.expression})`);
      }
    }

    const tableComment = schema.description ? ` COMMENT='${schema.description.replace(/'/g, "\\'")}'` : '';

    return [
      `-- Table: ${schema.tableName}`,
      `CREATE TABLE IF NOT EXISTS \`${schema.tableName}\` (`,
      lines.join(',\n'),
      `) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC${tableComment};`,
    ].join('\n');
  }

  /**
   * Formats a single column definition
   */
  private static formatColumnDefinition(name: string, col: ColumnDefinition): string {
    let typeStr: string = col.type;

    if (col.type === 'VARCHAR') {
      typeStr = `VARCHAR(${col.length || 255})`;
    } else if (col.type === 'DECIMAL') {
      typeStr = `DECIMAL(${col.precision || 10}, ${col.scale || 2})`;
    } else if (col.type === 'INTEGER') {
      typeStr = 'INT';
    } else if (col.type === 'BOOLEAN') {
      typeStr = 'TINYINT(1)';
    } else if (col.type === 'TIMESTAMP') {
      typeStr = 'DATETIME(6)';
    } else if (col.type === 'JSON' || col.type === 'JSONB') {
      typeStr = 'JSON';
    } else if (col.type === 'TEXT') {
      typeStr = 'TEXT';
    }

    const nullableStr = col.isNullable ? 'NULL' : 'NOT NULL';
    let defaultStr = '';
    if (col.defaultValue !== undefined) {
      if (typeof col.defaultValue === 'string' && col.defaultValue.toUpperCase().includes('CURRENT_TIMESTAMP')) {
        defaultStr = ' DEFAULT CURRENT_TIMESTAMP(6)';
      } else if (typeof col.defaultValue === 'boolean') {
        defaultStr = col.defaultValue ? ' DEFAULT 1' : ' DEFAULT 0';
      } else if (typeof col.defaultValue === 'number') {
        defaultStr = ` DEFAULT ${col.defaultValue}`;
      } else if (typeof col.defaultValue === 'string') {
        defaultStr = ` DEFAULT '${col.defaultValue.replace(/'/g, "\\'")}'`;
      }
    }

    const commentStr = col.description ? ` COMMENT '${col.description.replace(/'/g, "\\'")}'` : '';

    return `\`${name}\` ${typeStr} ${nullableStr}${defaultStr}${commentStr}`;
  }

  /**
   * Generates DDL for an entire schema list in topological order
   */
  public static generateAll(schemas: TableSchema[]): string {
    const ddlParts = [
      `-- ============================================================================`,
      `-- ShopSphere MySQL 8.0 Production DDL Schema Dump`,
      `-- Generated by ShopSphere Schema Engine`,
      `-- ============================================================================`,
      `SET FOREIGN_KEY_CHECKS = 0;`,
      ``,
    ];

    for (const schema of schemas) {
      ddlParts.push(this.generateCreateTable(schema));
      ddlParts.push('');
    }

    ddlParts.push(`SET FOREIGN_KEY_CHECKS = 1;`);
    return ddlParts.join('\n');
  }
}
